databases:
  - name: render-practice
    databaseName: render-practice
    user: render-practice

services:
  - type: web
    name: render-practice
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render-practice
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
