databases:
  - name: render_practice
    databaseName: render_practice_production
    user: render_practice

services:
  - type: web
    name: render_practice
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: render_practice
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
